### ISSUE TITLE
KEYS

### ISSUE THREAD

**Issue by mcowger** [thecodeteam/codedellemc.github.io#35]
Probably not a good idea to keep these keys in GitHub visible places :)

**Comment by JayCuthrell** [comment]
That's the combination to my luggage.

**Comment by jonasrosland** [comment]
Thanks for the report, keys are deleted from Twitter and the offending file is removed.

**Comment by kacole2** [comment]
the keys were in RO mode. couldn't have done much harm anyway. but pretty hard to expose ENV variables for a website and it only is available through a github folder :)
